name: Build C++ Project

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-make
    
    - name: Build with g++
      shell: msys2 {0}
      run: |
        g++ -std=c++23 fs.cpp -o fs.exe -municode
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-file-viewer
        path: fs.exe
